"""empty message

Revision ID: 332be5fae791
Revises: 2807edd385a2
Create Date: 2022-02-14 10:40:36.567526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '332be5fae791'
down_revision = '2807edd385a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###
